version: '3'
services:
  db:
    image: "mdillon/postgis"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  api:
    image: "postgrest/postgrest"
    environment:
      PGRST_DB_URI: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres"
      PGRST_DB_SCHEMA: "eventzimmer"
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_JWT_AUD: "api.eventzimmer.de"
      PGRST_ROLE_CLAIM_KEY: ".\"https://eventzimmer.de/role\""
    depends_on:
      - db
  docs:
    image: "swaggerapi/swagger-ui"
    depends_on:
      - api
