version: '3'
services:
  db:
    image: "mdillon/postgis"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - ./fixtures:/fixtures
  api:
    image: "postgrest/postgrest"
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres"
      PGRST_DB_SCHEMA: "eventzimmer"
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_JWT_AUD: "api.eventzimmer.de"
      PGRST_ROLE_CLAIM_KEY: ".\"https://eventzimmer.de/role\""
      PGRST_JWT_SECRET: "{\"alg\":\"RS256\",\"kty\":\"RSA\",\"use\":\"sig\",\"n\":\"6I3uazicRsIgn2HI1Jb_QNHAMN_QV3gWFKWSmy_nFgwogCoMqe0m7so6_D0-2xj2v5sLEyfgXeJc96UjRwtPVFfqTqdhaFYKPj1dzV3WguiOH-qTQdRUqVExyd4uJV1XPRfmw66_NyL7jMifuW4cOqaIT7Fp9EfwsypF-bxJcISvPcIqbZ1Ij86GHzx55gBG2iz0xiJlo2kcLLSW85uYo447RkS0hbvYnXhT0mza9DfCoTCo3d_YgeuxqsgkiwM82t_Y8trUwPzFK72PBi1GKulWTfj87wepMFTAmfVxMhoS_A4k5JtZyOxbqI10ZdwPl37iVPVqnkInb2Z0n2vghw\",\"e\":\"AQAB\",\"kid\":\"NUU5OTc5OUZCREM2QjE2MkUzQ0YwRTAwMDk4Q0VGMkM5MTNBQ0Q5Rg\"}"
      PGRST_SERVER_PROXY_URI: "http://localhost:3000"
    depends_on:
      - db
  docs:
    image: "swaggerapi/swagger-ui"
    environment:
      URL: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - api
